name: ave2
channels: !!python/tuple
- anaconda-fusion
- bioconda
- conda-forge
- defaults
dependencies:
- bioconda::bcftools=1.4=0
- bioconda::bedops=2.4.26=0
- bioconda::cyvcf2=0.7.2=py35_0
- bioconda::htslib=1.4=0
- bioconda::pybedtools=0.7.9=py35_0
- bioconda::pyfaidx=0.5.0=py35_0
- bioconda::pysam=0.11.0=py35_0
- bioconda::samtools=1.4=0
- bioconda::ucsc-bedtobigbed=332=0
- bioconda::ucsc-bigbedtobed=332=0
- bioconda::ucsc-bigBedInfo=332=0
- bioconda::ucsc-fatotwobit=332=0
- bioconda::ucsc-twobittofa=332=0
- bioconda::ucsc-twoBitInfo=332=0
- bioconda::bedtools=2.26.0
- conda-forge::curl=7.52.1=0
- conda-forge::numpy=1.12.1=py35_blas_openblas_200
- conda-forge::pip=9.0.1=py35_0
- conda-forge::scipy=0.19.0=np112py35_blas_openblas_200
- conda-forge::setuptools=33.1.1=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::python-levenshtein=0.12.0
- conda-forge::simplejson=3.1
- pip:
  - click==6.7
  - connexion==1.1.9
  - flask==0.12.1
  - flask-cors==3.0.3
  - requests==2.13.0
  - pytest==3.2.1
  - pytest-cov==2.5.1
  - whoosh==2.7.4
  - gunicorn==19.7.1
