name: ave2
channels: !!python/tuple
- anaconda-fusion
- bioconda
- conda-forge
- defaults
dependencies:
- bioconda::bcftools=1.4=0
- bioconda::bedops=2.4.26=0
- bioconda::cyvcf2=0.7.2=py35_0
- bioconda::htslib=1.4=0
- bioconda::pybedtools=0.7.9=py35_0
- bioconda::pyfaidx=0.4.8.1=py35_0
- bioconda::pysam=0.11.0=py35_0
- bioconda::python-dateutil=2.6.0=py35_0
- bioconda::samtools=1.4=0
- bioconda::ucsc-bedtobigbed=332=0
- bioconda::ucsc-fatotwobit=332=0
- bioconda::ucsc-twobittofa=332=0
- bioconda::ucsc-twoBitInfo=332=0
- conda-forge::blas=1.1=openblas
- conda-forge::bzip2=1.0.6=1
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py35_0
- conda-forge::curl=7.52.1=0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.11=py35_0
- conda-forge::freetype=2.7=1
- conda-forge::ipython=5.3.0=py35_0
- conda-forge::ipython_genutils=0.2.0=py35_0
- libgfortran=3.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::matplotlib=2.0.0=np112py35_3
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py35_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pandas=0.19.2=np112py35_1
- conda-forge::patsy=0.4.1=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::prompt_toolkit=1.0.14=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.2.0=py35_0
- conda-forge::pyparsing=2.2.0=py35_0
- conda-forge::python=3.5.3=1
- conda-forge::pytz=2017.2=py35_0
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py35_blas_openblas_200
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::setuptools=33.1.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::statsmodels=0.8.0=np112py35_0
- conda-forge::tk=8.5.19=1
- conda-forge::tornado=4.4.3=py35_0
- conda-forge::traitlets=4.3.2=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
- libgcc=4.8.5=1
- mkl=2017.0.1=0
- pip:
  - click==6.7
  - clickclick==1.2.1
  - connexion==1.1.9
  - editdistance==0.3.1
  - flask==0.12.1
  - flask-cors==3.0.3
  - inflection==0.3.1
  - ipython-genutils==0.2.0
  - itsdangerous==0.24
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - markupsafe==1.0
  - prompt-toolkit==1.0.14
  - pyyaml==3.12
  - requests==2.13.0
  - swagger-spec-validator==2.1.0
  - werkzeug==0.12.1
  - pyfaidx==0.5.0
  - python-Levenshtein
  - pytest==3.2.1
  - pytest-cov==2.5.1
