# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: AVE REST API
  description: Allelic Variation Explorer REST API, Serving variant, annotation and genome data for AVE visualisation.
  version: {{VERSION}}
{% if HOSTPORT is defined %}
# the domain of the service
host: {{HOSTPORT}}
{% endif %}
{% if SCHEME is defined %}
# array of all schemes that your API supports
schemes:
  - {{SCHEME}}
{% endif %}
# will be prefixed to all paths
basePath: /api/
produces:
  - application/json
  - application/problem+json
paths:
  /species:
    get:
      operationId: avedata.api.species.search
      summary: List of species
      description: |
        Fetch list of the species with available data.
      tags:
        - Species
      responses:
        200:
          description: Array of the speecies names
          schema:
            type: array
            items:
              $ref: '#/definitions/Species'
          examples:
            application/json: [{'name': 'Solanum lycopersicum',
                               'species_id': 'Solanum%20Lycopersicum'},
                               {'name': 'Arabidopsis thaliana',
                                'species_id': 'Arabidopsis%thaliana'}]
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /species/{species_id}/genomes:
    get:
      operationId: avedata.api.species.genomes
      summary: Genomes of selected species
      description: |
        List of genomes available for this species id
      parameters:
        - name: species_id
          in: path
          description: Species identifier
          required: true
          type: string
      tags:
        - Species
      responses:
        200:
          description: Genomes of selected species
          schema:
            type: array
            items:
              $ref: '#/definitions/Genome'
          examples:
            application/json: [{'genome_id': 'SL.2.40',
                                'chromosomes': [
                                  {'chrom_id': 'SL2.40ch00',
                                   'length': '21805821'},
                                  {'chrom_id': 'SL2.40ch01',
                                   'length': '90304244'},
                                ],
                                'feature_types': [],
                                'accessions': [
                                  'RF_001_SZAXPI008746-45',
                                  'RF_002_SZAXPI009284-57',
                                  'RF_003_SZAXPI009285-62'],
                                'reference': 'latest/tomato/S_lycopersicum_chromosomes.2.40.2bit',
                                'gene_track': 'latest/tomato/S_lycopersicum_May_2012.bb'},
                                ]
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /genomes/{genome_id}:
    get:
      operationId: avedata.api.genomes.get
      summary: Genome information of selected genome
      description: |
        Genome information for selected genome
      parameters:
        - name: genome_id
          in: path
          description: Genome id
          required: true
          type: string
      tags:
        - Genomes
      responses:
        200:
          description: Detailed information about the genome with genome_id
          schema:
            $ref: '#/definitions/Genome'
          examples:
            application/json: {
              "accessions": [
                "RF_001_SZAXPI008746-45",
                "RF_002_SZAXPI009284-57",
                "RF_003_SZAXPI009285-62"
              ],
              "chromosomes": [
                {"chrom_id": "SL2.40ch00",
                 "length": 21805821},
                {"chrom_id": "SL2.40ch01",
                 "length": 90304244
                }
              ],
              "feature_types": [],
              "gene_track": "latest/tomato/S_lycopersicum_May_2012.bb",
              "genome_id": "SL.2.40",
              "reference": "latest/tomato/S_lycopersicum_chromosomes.2.40.2bit"
            }

  /genomes/{genome_id}/chromosomes/{chrom_id}/start/{start_position}/end/{end_position}/haplotypes:
    get:
      operationId: avedata.api.genomes.haplotypes
      summary: Genomic variants of the genomic region
      description: |
        Genomic variants of genomic region of selected genome, chromosome from start position to end position
      parameters:
        - name: genome_id
          in: path
          description: Genome id
          required: true
          type: string
        - name: chrom_id
          in: path
          description: Chromosome id
          required: true
          type: string
        - name: start_position
          in: path
          description: Start Position
          required: true
          type: integer
        - name: end_position
          in: path
          description: End Position
          required: true
          type: integer
        - name: accessions
          description: Calculate haplotypes on subset of accessions
          in: query
          type: array
          items:
            type: string
          minItems: 0
      tags:
        - Genomes
      responses:
        200:
          description: Array of genomic variants for selected genome id
          schema:
            $ref: '#/definitions/Haplotypes'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /genomes/{genome_id}/genes:
    get:
      operationId: avedata.api.genomes.gene_search
      parameters:
        - name: genome_id
          in: path
          description: Genome id
          required: true
          type: string
        - name: query
          in: query
          type: string
          required: true
      tags:
      - Genomes
      responses:
        200:
          description: Top ten search results
          schema:
            type: array
            items:
              $ref: '#/definitions/GeneSearchResult'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /genomes/{genome_id}/features:
    get:
      operationId: avedata.api.genomes.feature_search
      parameters:
        - name: genome_id
          in: path
          description: Genome id
          required: true
          type: string
        - name: query
          in: query
          type: string
          required: true
      tags:
      - Genomes
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              $ref: '#/definitions/FeatureSearchResult'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    description: >-
      Problem Details for HTTP APIs, see
      https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00
    properties:
      status:
        type: integer
        format: int32
      type:
        type: string
      detail:
        type: string
      title:
        type: string
    required:
    - status
    - type
    - title
    - detail
  Species:
    type: object
    description: |
      Species information
    properties:
      name:
        type: string
        example: Solanum lycopersicum
      species_id:
        type: string
        example: Solanum_lycopersicum
        description: URI friendly species identifier
    required:
    - name
    - species_id
  FeatureSearchResult:
    type: object
    properties:
      chrom:
        description: name of the sequence (typically a chromosome)
        type: string
      start:
        description: start of the feature
        type: integer
      end:
        description: end of the feature
        type: integer
      name:
        description: Feature identifier
        type: string
      attributes:
        type: string
      track:
        description: Feature track name
        type: string
    required:
    - chrom
    - start
    - end
    - name
    - attributes
    - track
  GeneSearchResult:
    type: object
    properties:
      chrom:
        description: name of the sequence (typically a chromosome)
        type: string
      start:
        description: start of the transcript
        type: integer
      end:
        description: end of the transcript
        type: integer
      id:
        description: Transcript identifier
        type: string
      gene_id:
        type: string
      name:
        type: string
    required:
    - chrom
    - start
    - end
    - id
    - gene_id
    - name
  Genotype:
    type: object
    properties:
      accession:
        type: string
      alt_ambiguous_nucleotide:
        type: string
        description: The list of alternative alleles at this position mapped to an ambiguous nucleotide
      is_homozygous:
        type: boolean
        description: Whether genoytype is heterozygous or homozygous
    additionalProperties:
      type: string
    required:
      - accession
      - alt_ambiguous_nucleotide
      - is_homozygous
  Variant:
    type: object
    description: |
      Genomic Variant as in vcf description
      https://en.wikipedia.org/wiki/Variant_Call_Format
    properties:
      chrom:
        type: string
        description: |
          The name of the sequence (typically a chromosome) on which the variation is being called.
          This sequence is usually known as 'the reference sequence',
          i.e. the sequence against which the given sample varies.
      pos:
        type: integer
        minimum: 1
        description: |
          The 1-based position of the variation on the given sequence.
      id:
        type: string
        description: |
          The identifier of the variation, e.g. a dbSNP rs identifier or just . if unknown. Multiple identifiers should be separated by semi-colons without white-space.
      ref:
        type: string
        description: |
          The reference base (or bases in the case of an indel) at the given position on the given reference sequence.
      alt:
        type: array
        description: The list of alternative alleles at this position
        items:
          type: string
      qual:
        type: number
        description: A quality score associated with the inference of the given alleles.
      filter:
        type: string
        description: A flag indicating which of a given set of filters the variation has passed.
      info:
        type: object
        additionalProperties:
          type: string
        description: Variation description
      genotypes:
        type: array
        description: Genotype information for accession and position
        items:
          $ref: '#/definitions/Genotype'
    required:
    - chrom
    - pos
    - id
    - ref
    - alt
    - qual
    - filter
    - info
    - genotypes
  Chromosome:
    type: object
    description: |
      Chromosome information
    properties:
      chrom_id:
        type: string
      length:
        type: integer
    required:
    - chrom_id
    - length
  Track:
    type: object
    properties:
      label:
        type: string
      url:
        type: string
        format: uri
        description: URL of bigBed file with feature annotations
    required:
    - label
    - url
  Genome:
    type: object
    properties:
      genome_id:
        type: string
      chromosomes:
        type: array
        items:
          $ref: '#/definitions/Chromosome'
      feature_tracks:
        type: array
        items:
          $ref: '#/definitions/Track'
      accessions:
        description: Available accession for genome. Used to give list of accessions for haplotype to filter on.
        type: array
        items:
          type: string
      reference:
        type: string
        format: uri
        description: URL of 2bit file
      gene_track:
        type: string
        format: uri
        description: URL of bigBed file with gene annotations
      species:
        $ref: '#/definitions/Species'
      variants_filename:
        type: string
        description: File name of variants (bcf) file
    required:
    - genome_id
    - chromosomes
    - feature_tracks
    - accessions
    - reference
    - species
  HaplotypeNode:
    type: object
    properties:
      haplotype_id:
        type: string
      children:
        type: array
        items:
          $ref: '#/definitions/HaplotypeNode'
  Haplotype:
    type: object
    properties:
      haplotype_id:
        type: string
      accessions:
        description: Available accession for haplotype.
        type: array
        items:
          type: string
      variants:
        type: array
        items:
          $ref: '#/definitions/Variant'
      sequence:
        type: string
        description: DNA sequence of the haplotype. Reference with variants.
    required:
    - haplotype_id
    - accessions
    - variants
    - sequence
  Haplotypes:
    type: object
    properties:
      hierarchy:
        $ref: '#/definitions/HaplotypeNode'
      haplotypes:
        type: array
        items:
          $ref: '#/definitions/Haplotype'
    required:
    - hierarchy
    - haplotypes
